# Build settings
# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "with_toc_data", "fenced_code_blocks"]
highlighter: pygments

# Site settings
title: "Pete App Designs"
description: ""

email: "pierremarcairoldi@gmail.com"
# # blog logo
# logo: "PM"
# # blog cover
# cover: "/assets/images/Life-of-Pix-free-stock-photo-city-Montreal-skyline.jpg"

name: "Pierre-Marc Airoldi"
author: "Pierre-Marc Airoldi"
author_image: ""

paginate: 10

url: "/" # the base hostname & protocol for your site
baseurl: ""
permalink: /:title/

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/petester42
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/petester42
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

exclude: [vendor, "Gemfile", "Gemfile.lock", "Rakefile", "LICENCE", "README.md", "staging", "production", "pages/about.md", "pages/portfolio.md"]
gems: [jekyll-paginate]
